### ISSUE TITLE
Last release tag does not match actual last tag

### ISSUE THREAD

**Issue by oSumAtrIX** [droidsolutions/semantic-release-update-file#694]
Run: https://github.com/ReVanced/revanced-manager/actions/runs/8149743168/job/22274900548

For some reason this returns 1.18.0: https://github.com/droidsolutions/semantic-release-update-file/blob/main/lib/prepare.ts#L46
Instead, it should return the last tag. It seems like `context.lastRelease` returns the last non-prerelease which indeed is 1.18.0

**Comment by Kampfmoehre** [comment]
Is there a tag for the last version you had? Semantic Release pulls the tags you have and determines the last release from there. If you ever manually overwrite the version in `pubspec.yaml` this can become out of sync. This can get annoying but should not happen if all releases are performed by SR.

**Comment by oSumAtrIX** [comment]
Hey, how would I test this?

**Comment by Kampfmoehre** [comment]
:tada: This fix is included in version 1.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@droidsolutions-oss/semantic-release-update-file/v/1.4.0)
- [GitHub release](https://github.com/droidsolutions/semantic-release-update-file/releases/tag/v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
